version: '3.7'

services:
  web:
    build: .
    command: sh entrypoint.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - 8005:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.12-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev.db
# /var/lib/docker/volumes
volumes:
    postgres_data: