# docker-compose.prod.yml
version: '3.7'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn biz.wsgi:application --bind 0.0.0.0:8010
    volumes:
      - /static:/home/app/web/static
      - /media:/home/app/web/media
    ports:
      - 8010:8010
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    restart: always
    image: postgres:12.2-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

#  /var/lib/docker/volumes
volumes:
  postgres_data_prod: