# Generated by Django 4.0.7 on 2022-09-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'B2B main page'},
        ),
    ]
