# Generated by Django 4.0.7 on 2022-09-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsinfo', '0004_projectallnews_projectnews_parent_prj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectnews',
            name='parent_prj',
        ),
    ]
