# Generated by Django 4.0.7 on 2022-08-24 19:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='parameters',
            field=wagtail.fields.StreamField([('params', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add parameter name', required=True)), ('params', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=60, required=True)), ('param', wagtail.blocks.CharBlock(max_length=60, required=True))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
